services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    volumes:
      - heimdall:/config
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.rpi.local`)"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
networks:
  traefik_proxy:
    external: true
volumes:
  heimdall:
    driver: local
